### ISSUE TITLE
error on pip install ... - Ubuntu 12.04 running python 2.7.

### ISSUE THREAD

**Issue by DiagonalArg** [cpbotha/nvpy#124] opened 2015-05-30 15:45 UTC
Tried to do the install, but got the following errors.  I see ubuntu packages "tk" and "tcl" installed, but I don't see any mention of "tkinter" in the repositories.  I get similar errors on "sudo pip install nvpy" and (see below) "easy_install nvpy" crashes easy_install.  (I don't know enough about python to make any more sense of the errors...)

```
sudo pip install 'git+https://github.com/cpbotha/nvpy.git#egg=nvpy'
Downloading/unpacking git+https://github.com/cpbotha/nvpy.git#egg=nvpy
  Cloning https://github.com/cpbotha/nvpy.git to /tmp/pip-DpR9ES-build
  Running setup.py egg_info for package from git+https://github.com/cpbotha/nvpy.git#egg=nvpy
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/tmp/pip-DpR9ES-build/setup.py", line 3, in <module>
        from nvpy import nvpy
      File "nvpy/nvpy.py", line 43, in <module>
        import view
      File "nvpy/view.py", line 9, in <module>
        import search_entry
      File "nvpy/search_entry.py", line 11, in <module>
        import tkinter as Tkinter
    ImportError: No module named tkinter
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>
  File "/tmp/pip-DpR9ES-build/setup.py", line 3, in <module>
    from nvpy import nvpy
  File "nvpy/nvpy.py", line 43, in <module>
    import view
  File "nvpy/view.py", line 9, in <module>
    import search_entry
  File "nvpy/search_entry.py", line 11, in <module>
    import tkinter as Tkinter

ImportError: No module named tkinter
----------------------------------------
Command python setup.py egg_info failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 980, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 216, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 255, in call_subprocess
```

"sudo easy_install nvpy" causes easy_install to crash:

```
sudo easy_install nvpy
Searching for nvpy
Reading http://pypi.python.org/simple/nvpy/
Best match: nvpy 0.9.4
Downloading https://pypi.python.org/packages/source/n/nvpy/nvpy-0.9.4.tar.gz#md5=7e0fc1d3266418283d0a7f7d36679d8e
Processing nvpy-0.9.4.tar.gz
Running nvpy-0.9.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-mSB7Bl/nvpy-0.9.4/egg-dist-tmp-QifOvr
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 9, in <module>
    load_entry_point('distribute==0.6.24dev-r0', 'console_scripts', 'easy_install')()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1931, in main
    with_ei_usage(lambda:
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1912, in with_ei_usage
    return f()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1935, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 368, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 608, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 638, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 828, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1105, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1094, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 30, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 72, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 32, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 3, in <module>
  File "/tmp/easy_install-mSB7Bl/nvpy-0.9.4/nvpy/nvpy.py", line 43, in <module>
  File "/tmp/easy_install-mSB7Bl/nvpy-0.9.4/nvpy/view.py", line 9, in <module>
  File "/tmp/easy_install-mSB7Bl/nvpy-0.9.4/nvpy/search_entry.py", line 11, in <module>
ImportError: No module named tkinter
```

**Comment by DiagonalArg** [comment] 2015-05-30 16:07
Ok, had to "apt-get install python-tk".  That should be mentioned in the install instructions, huh?

Thanks -
/DA.

**Comment by ernstki** [comment] 2020-01-16 18:15
Hello from the year 2020! Tkinter is still required, and if you're using a Python 3.x variant, installed with `pip3`, you'll want to 

```
package-manager install python3-tk
```

…replacing `package-manager` with `apt` or `yum` or whatever is appropriate for your distro.

This is a duplicate of #66.

**Closed** 2023-09-26 16:05 UTC
