### ISSUE TITLE
Text too light

### ISSUE THREAD

**Issue by crazzyfool** [cpbotha/nvpy#170] opened 2019-01-02 10:05 UTC
The text is too light I can hardly read it.  How can this be changed?

![nvpy_008](https://user-images.githubusercontent.com/10143249/50587437-d8a27a00-0e75-11e9-958e-7d5605b2c680.png)

**Comment by crazzyfool** [comment] 2019-01-03 10:45
Is there a "font_color=black" setting I can add to ~/.nvpy.cfg for example?  Not sure where its getting this light grey colour from?!

**Comment by yuuki0xff** [comment] 2019-01-03 12:13
Duplicate of #163

**Closed by yuuki0xff** 2019-01-03 12:13 UTC
Labels: duplicate
